/*
 * File:   system_settings.h
 * Author: simonn
 */

#ifndef FIRMWARE_SRC_SYSTEM_CONFIG_MX_795_512L_SYSTEM_SETTINGS_H_
#define FIRMWARE_SRC_SYSTEM_CONFIG_MX_795_512L_SYSTEM_SETTINGS_H_

#ifdef __cplusplus
extern "C" {
#endif

#define RDM_RESPONDER_PORT PORT_CHANNEL_D
#define RDM_RESPONDER_IDENTIFY_PORT_BIT PORTS_BIT_POS_0
#define RDM_RESPONDER_MUTE_PORT_BIT PORTS_BIT_POS_11
#define TRANSCEIVER_UART USART_ID_5
#define TRANSCEIVER_PORT PORT_CHANNEL_B
#define TRANSCEIVER_PORT_BIT PORTS_BIT_POS_14
#define TRANSCEIVER_TX_ENABLE PORTS_BIT_POS_9
#define TRANSCEIVER_RX_ENABLE PORTS_BIT_POS_10

// DMX RX to SPI
#define SPI_MODULE_ID SPI_ID_2
#define SPI_BAUD_RATE 1000000u

#ifdef __cplusplus
}
#endif

/**
 * @}
 */

#endif  // FIRMWARE_SRC_SYSTEM_CONFIG_MX_795_512L_SYSTEM_SETTINGS_H_
